export enum EnemyFightActionTypes {
  SET_ENEMY_ATTACK = 'SET_ENEMY_ATTACK',
  SET_ENEMY_DEFENCE = 'SET_ENEMY_DEFENCE',
  SET_ENEMY_READY = 'SET_ENEMY_READY',
  CLEAR_ENEMY_FIGHT_STORE = 'CLEAR_ENEMY_FIGHT_STORE',
}
