export enum UserFightActionTypes {
  SET_ATTACK = 'SET_ATTACK',
  RM_ATTACK = 'RM_ATTACK',
  SET_DEFENCE = 'SET_DEFENCE',
  RM_DEFENCE = 'RM_DEFENCE',
  SET_USER_READY = 'SET_USER_READY',
  CLEAR_USER_FIGHT_STATE = 'CLEAR_USER_FIGHT_STATE',
}
